name: Automatic Merge on Dependabot Pull Request
on:
  pull_request:
    branches: [ develop ]

jobs:
  merge-pr:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })

#  build_and_release:
#    needs: merge-pr
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup Node.js
#        uses: actions/setup-node@v2-beta
#        with:
#          node-version: '14'
#
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          ref: ${{ github.head_ref }}
#          fetch-depth: 0
#
#      - name: Fetch Dependencies (Server)
#        run: yarn install --ignore-scripts
#        working-directory: /server
#
#      - name: Build (Server)
#        run: yarn run build --if-present
#        working-directory: /server
#
#      - name: Bump Version (Server)
#        run: yarn version --no-git-tag-version --new-version patch
#        working-directory: /server
#
#      - name: Fetch Dependencies (Client)
#        run: yarn install --ignore-scripts
#        working-directory: /client
#
#      - name: Build (Client)
#        run: yarn run build --if-present
#        working-directory: /client
#
#      - name: Bump Version (Client)
#        run: yarn version --no-git-tag-version --new-version patch
#        working-directory: /client
#
#      - name: Commit and Push
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Release new version for automatic PR merging.
#          branch: develop
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
